version: '3.9'

services:
  development:
    build:
      context: .
    container_name: mutual-api-dev
    env_file: .env.development
    entrypoint: npm run start:docker
    ports:
      - 3000:3000
    depends_on:
      - database
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - api-net

  database:
    image: mongo
    container_name: mutual-db
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo_user
      - MONGO_INITDB_ROOT_PASSWORD=mongo_password
      - MONGO_INITDB_DATABASE=admin
    volumes:
      - db-volume:/data/db
    networks:
      - api-net

volumes:
  db-volume:

networks:
  api-net:

